### ISSUE TITLE
Rewrite in Rust :crab: 

### ISSUE THREAD

**Issue by mgonzalezperna** [skalanux/notengowifi#1]
This is a very cool project. However, have you considered rewriting it in rust?
Rust is a systems programming language that runs blazingly fast :rocket:, prevents segfaults, and guarantees thread safety.

I think your novel wireless communication protocol would benefit greatly from it.

**Comment by cripton** [comment]
> This is a very cool project. However, have you considered rewriting it in rust? Rust is a systems programming language that runs blazingly fast 🚀, prevents segfaults, and guarantees thread safety.
> 
> I think your novel wireless communication protocol would benefit greatly from it.

go with your orthodox-rust-televangelism somewhere else
